### PR TITLE
[#168791451] Add Azure blob storage container option

### PR DESCRIPTION
**Pull request by aoldershaw**
Signed-off-by: Dimitry Besson <dbesson@pivotal.io>

### CODE REVIEW

**Comment by jncd** [comment]
Hi @dimitrybesson and @aoldershaw 
Thank you for this very nice PR. Are we going to need a new screenshot too? One that includes the new Azure Blob Storage button?
Screen Shot 2019-10-09 at 10 59 37 AM

**Comment by aoldershaw** [comment]
> Thank you for this very nice PR. Are we going to need a new screenshot too? One that includes the new Azure Blob Storage button?

Hi Jane,

Yes, we'll need a new screenshot as the tile changed. Should we produce the screenshot, or is that something you can do? Would you need us to provide you with an Ops Manager environment with the tile staged?

**Comment by jncd** [comment]
Hi @aoldershaw If you have an Ops Manage environment with a tile available — and can share the creds, that would be perfect. LMK

**Comment by aoldershaw** [comment]
@jncd I've pinged you on Slack

**Pull request merged**
